name: GitHub Org xplore-org Node.js CI Starter Workflow

# Documentation:
# https://docs.github.com/en/actions/how-tos/reuse-automations/create-workflow-templates
# https://docs.github.com/en/actions/reference/workflows-and-actions/reusing-workflow-configurations#workflow-templates

on:
  push:
    branches: [ $default-branch ]
  pull_request:
    branches: [ $default-branch ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js Version 20.x
        uses: actions/setup-node@v5
        with:
          node-version: '20.x'

      - name: Install dependencies
        run: npm install

      - name: Run Unit tests
        run: npm test --if-present
      
      - name: Run Coverage Report
        run: npm run coverage --if-present
